#!/bin/sh

git submodule sync
git submodule update --init


mkdir -p addons

# GdUnit
rm -rf ./addons/gdUnit4
ln -s -r -P .submodules/gdUnit4/addons/gdUnit4 ./addons/
# Remove GdUnit4 tests
TARGET_DIR="addons/gdUnit4/test"
if [ -d "$TARGET_DIR" ]; then
	echo "Removing GdUnit4 test directory"
	rm -rf "$TARGET_DIR"
fi

# Uncomment this to setup the GodotInSim addon directory symlink
## GodotInSim
#rm -rf ./addons/godot_insim
#ln -s -r -P .submodules/godot_insim/addons/godot_insim ./addons/
## Remove GodotInSim tests
#TARGET_DIR="addons/godot_insim/test"
#if [ -d "$TARGET_DIR" ]; then
#	echo "Removing GodotInSim test directory"
#	rm -rf "$TARGET_DIR"
#fi
