image: registry.gitlab.com/cykyrios/godot-builder:4.5-beta4-editor

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never

stages:
  - test
  - export
  - docs
  - deploy

variables:
  # Update submodules and force https
  # (doesn't seem to work for submodules hosted on GitHub, update .gitmodules manually)
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

run-tests:
  stage: test
  image: registry.gitlab.com/cykyrios/godot-builder:4.4.1-editor
  script:
    - rm -rf addons/gdUnit4/test
    - godot --headless -v --import
    - sed -E -i '/gdscript\/warnings\/.+?/a gdscript\/warnings\/redundant_await=0' project.godot
    - export GODOT_BIN=$(which godot)
    - ./addons/gdUnit4/runtest.sh --headless --ignoreHeadlessMode -c -a addons/godot_insim/test
  artifacts:
    when: always
    name: "Test Report"
    paths:
      - reports/
    reports:
      junit: reports/**/results.xml

export-demos:
  stage: export
  needs: [run-tests]
  image: registry.gitlab.com/cykyrios/godot-builder:4.5-beta4-desktop
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    package_registry_url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic"
  before_script:
    - apt-get update && apt-get install -y curl zip
  script:
    - godot --headless -v --import
    - sh ./export_demos.sh
    - |
      cd build
      for demo in */; do
        cd "$demo"
        for platform in */; do
          cd "$platform"
          binary_archive="${demo////}_v${CI_COMMIT_TAG}_${platform////}.zip"
          zip -r "$binary_archive" *
          curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
            --upload-file "$binary_archive" \
            ${package_registry_url}/demos/${CI_COMMIT_TAG}/${binary_archive}
          cd ..
        done
        cd ..
      done

generate-docs:
  stage: docs
  needs: []
  ## The image used here contains a doctool fix, see Godot PR #106256.
  image: registry.gitlab.com/cykyrios/godot-builder:4.5-beta4-docs-generator
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git
    - godot --headless -v --import
    - godot --headless -s ./docs_generator/generate_docs.gd
  artifacts:
    paths:
      - website/classref_sidebar.ts
      - website/docs/class_ref/*.mdx

build-site:
  stage: docs
  needs: [generate-docs]
  image: node:lts-alpine3.20
  script:
    - cd website
    - npm install
    - npm run build
  artifacts:
    paths:
      - website/build/

deploy-site:
  stage: deploy
  needs: [build-site]
  image: alpine:3.20
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Deploying to GitLab Pages"
  pages:
    publish: website/build
